import random
""" 
This is a fruit name guessing game in which a user will guess the name of a fruit randomly selected by the program
The user will enter a letter at a time and each time they enter a letter that is not in the selected fruit they lose a life
The user gets 3 lives, meaning if they get 3 letters wrong of the fruit, the game ends for them.
The game also ends as soons as the user types in "*".
"""
# asks the user if they want to play the game or not
def get_consent():
    consent = input("Do you want to play the fruit guessing game type 'y' for yes and 'n' type no ")
    consent = consent.strip()
    consent = consent.lower()
    while consent != 'y' and consent != 'n':
        print("invalid input , try again ")
        consent = input("do you want to play the fruit guessing game for yes type 'y' for no type 'n' ")
        consent = consent.strip()
        consent = consent.lower()
    return consent
# this is the function that deals with the game being  played     
def game(fruitList):
    # randomly choosing a fruit
    i= random.randint(0,len(fruitList)-1)
    fruitChosenByAlgorithm = fruitList[i]
    print(fruitChosenByAlgorithm) # delete later 
    # right now the guessed word is empty
    blanksForInputs = ["_"] * len(fruitChosenByAlgorithm)
    # the user guessing the letter that goes in the blanks
    lives = 3
    print(blanksForInputs)
    while lives > 0 and "_" in blanksForInputs:
        userGuessLetter = input("Enter a letter that might be in the fruit: ")
        
        if userGuessLetter in fruitChosenByAlgorithm:
            for index, letter in enumerate(fruitChosenByAlgorithm) :
                if letter == userGuessLetter:
                    blanksForInputs[index] = userGuessLetter #make the letter go where is should in the blanks according in index of the fruitChosenByAlgorithm
            print("You are on the right track")
            print(blanksForInputs)
        else: # if the letter that the user input is not in the fruitChosenByAlgorithm
            print("Your input was wrong, make sure the letter is in the fruit picked by the function and input one at a time")
            print("You lost a life")
            lives = lives -1
        
        if "".join(blanksForInputs) == fruitChosenByAlgorithm: # This line was generated by chatgpt
            print("Success! You guessed the fruit:", fruitChosenByAlgorithm)
            break
            
                
        
       
# tells the user how to the game will be played
def rules():
    fruitList = ["apple","orange","kiwi","mango","pineapple"]
    print("------------------------------------------------------------------------------------------------------------------------------------------------------------------")
    print("Welcome to the fruit guessing game")
    print(f"From the list of fruit [{fruitList}] you have to guess a randomly selected fruit")
    print("You will enter a letter at a time and get three live")
    print("If you get a letter wrong you will lose a life")
    print("Anytime you want to exit the game entre the symbol '*' the game ends ")
    print("------------------------------------------------------------------------------------------------------------------------------------------------------------------")
    return fruitList
# the function where the other parameters will be called.
def controller():
    fruitList=rules()
    if get_consent() == 'y':
        game(fruitList)
    else:
        print("Have a good day. Lets play next time")
controller()